### ISSUE TITLE
Import scss into pcss?

### ISSUE THREAD

**Issue by rowild** [king-prawns/webpack4-starter-kit#2]
Sorry, if this is the wrong place to post a question - please redirect me to the proper place, if there is one!

I was wondering if it is possible to import scss files into the index.pcss, and if so, what would a configuration for a proper loader look like in this case?

Thank you!

**Comment by king-prawns** [comment]
Hi @rowild ,
No, it's not possible.
But I can suggest two ways that could help you:
- generate a bundle for .scss and a different bundle for .pcss with the right loaders
- follow [this approach](https://tylergaw.com/articles/sass-to-postcss/) to migrate from scss to pcss

FYI [Here](https://github.com/king-prawns/webpack4-starter-kit/blob/15d6c2a92977e50e729424527517591b172b66ae/config/webpack.dev.conf.js#L46) you can find the right configuration for handle .scss files.

**Comment by rowild** [comment]
Thanks a lot for your quick response and the valuable information!

**Comment by king-prawns** [comment]
You are welcome
